### ISSUE TITLE
I'm working on a list of suspicious download sites, would appreciate if it could be included

### ISSUE THREAD

**Issue by ngoomie** [rjaus/awesome-ublacklist#10]
https://github.com/ngoomie/uBlacklist-suspicious-downloads

It's pretty small right now, but I'm working on expanding it (and I hope that it being included in this list might get more people to come and help). The biggest/worst English-language sites are here (like Softonic) but I'm probably missing large sites of a similar nature whose primary audience is people who don't speak English.

**Comment by rjaus** [comment]
Happy to include it, just submit a PR
