### ISSUE TITLE
Where's your uBlacklist.txt file???

### ISSUE THREAD

**Issue by gggirlgeek** [rjaus/awesome-ublacklist#5]
I see no uBlacklist.txt file listed here. What am I missing?

**Comment by rjaus** [comment]
Heya. The intent is that this awesome list is a list of repos which contain uBlacklist for specific purposes.

You can then add those blacklists to the uBlacklist app as subscriptions. They will then auto update as those repos are updated.

Having specific repos for each type of blacklist (social, Pinterest, e-commerce, dev blog spam) enables the user to more specifically decide what they want to block, without having to manage keeping their own blacklist up to date.

**Comment by rjaus** [comment]
The readme contains an explanation of this. Is it unclear? Happy to take PRs
